type User {
  _id: ID
  login: String!
  bio: String!
  contatos : [Contato]
  token: String!
}

input UserInput {
  login: String!
  bio: String!
}

type Query {
  users: [User!]!
  user(login: String): User!
}

type Mutation {
  createUser(data: UserInput): User!
  updateUser(id: ID, data: UserInput): User!
  deleteUser(id: ID): Boolean
}
